#!/bin/bash

set -Eeuo pipefail

#. ./default.cfg
#
#if [ -e "custom.cfg" ]; then
#	. ./custom.cfg
#fi

./scripts/01-setup-network
./scripts/02-prepare-files
./scripts/03-launch-boot-server
./scripts/04-configure-boot-server
./scripts/05-launch-qtest-server
./scripts/06-configure-qtest1
./scripts/07-setup-user-bob
./scripts/08-setup-icinga
