#!/bin/bash

set -Eeuo pipefail
cd "${0%/*}"
. ./functions.sh

info "####################"
info "# NETWORKING SETUP #"
info "####################"

if ! ip link show "${DL_BRIDGE_NAME}" > /dev/null 2>&1; then
	info "Creating bridge device ${DL_BRIDGE_NAME}"
	sudo ip link add "${DL_BRIDGE_NAME}" type bridge
else
	info "Bridge device ${DL_BRIDGE_NAME} already exists"
fi

info "Setting address on bridge device ${DL_BRIDGE_NAME} to ${DL_BRIDGE_ADDRESS}/${DL_BRIDGE_PREFIX_LEN}"
sudo ip addr add "${DL_BRIDGE_ADDRESS}/${DL_BRIDGE_PREFIX_LEN}" dev "${DL_BRIDGE_NAME}" > /dev/null 2>&1 || true

info "Bringing up bridge device ${DL_BRIDGE_NAME}"
sudo ip link set "${DL_BRIDGE_NAME}" up qlen 10000

if ! sudo iptables -t nat -C POSTROUTING			\
	  -s "${DL_BRIDGE_PREFIX}/${DL_BRIDGE_PREFIX_LEN}"	\
	! -d "${DL_BRIDGE_PREFIX}/${DL_BRIDGE_PREFIX_LEN}"	\
	  -m comment --comment="debops-lab"			\
	  -j MASQUERADE > /dev/null 2>&1; then
	info "Adding firewall masquerade rule for bridge network egress"
	sudo iptables -t nat -A POSTROUTING				\
		  -s "${DL_BRIDGE_PREFIX}/${DL_BRIDGE_PREFIX_LEN}"	\
		! -d "${DL_BRIDGE_PREFIX}/${DL_BRIDGE_PREFIX_LEN}"	\
		  -m comment --comment="debops-lab"			\
		  -j MASQUERADE
else
	info "Firewall masquerade rule for bridge network egress already exists"
fi

if ! sudo iptables -t filter -C FORWARD				\
	  -i "${DL_BRIDGE_NAME}"				\
	! -o "${DL_BRIDGE_NAME}"				\
	  -s "${DL_BRIDGE_PREFIX}/${DL_BRIDGE_PREFIX_LEN}"	\
	! -d "${DL_BRIDGE_PREFIX}/${DL_BRIDGE_PREFIX_LEN}"	\
	  -m comment --comment="debops-lab"			\
	  -j ACCEPT > /dev/null 2>&1; then
	info "Adding firewall forwarding rule for bridge network egress"
	sudo iptables -t filter -I FORWARD 1				\
		  -i "${DL_BRIDGE_NAME}"				\
		! -o "${DL_BRIDGE_NAME}"				\
		  -s "${DL_BRIDGE_PREFIX}/${DL_BRIDGE_PREFIX_LEN}"	\
		! -d "${DL_BRIDGE_PREFIX}/${DL_BRIDGE_PREFIX_LEN}"	\
		  -m comment --comment="debops-lab"			\
		  -j ACCEPT
else
	info "Firewall forwarding rule for bridge network egress already exists"
fi

function add_tap {
	local TAPDEV="${1}"

	if ! ip link show "${TAPDEV}" > /dev/null 2>&1; then
		info "Adding network device ${TAPDEV}"
		sudo ip tuntap add dev "${TAPDEV}" mode tap user "${USER}"
	else
		info "Network device ${1} already exists"
	fi
	sudo ip link set "${TAPDEV}" master "${DL_BRIDGE_NAME}"
	sudo ip link set "${TAPDEV}" up qlen 10000
}

add_tap tap253
add_tap tap1
add_tap tap2
add_tap tap3

info "Setting up IPv4 forwarding"
sudo sh -c 'echo 1 >> /proc/sys/net/ipv4/ip_forward'

info ""
exit 0
