#!/bin/bash

set -Eeuo pipefail
cd "${0%/*}"
. ./functions.sh

info "####################"
info "# FILE PREPARATION #"
info "####################"

if [ ! -d "tmp" ]; then
	mkdir "tmp"
fi
cd "tmp"

function get_file {
	local file="$1"
	local uri="$2"

	if [ -e "${file}" ]; then
		info "Checking for an updated ${file}"
		zflag=(-z "${file}")
	else
		info "Downloading file ${file}"
		zflag=()
	fi
	curl -s -o "${file}" "${zflag[@]}" "$uri"
}

get_file "initrd.gz" "${DL_INITRD_URL}"
get_file "linux" "${DL_KERNEL_URL}"

if [ ! -e "../files/preseed.cfg" ]; then
	info "Preseed file missing"
	exit 1
elif [ ! -e "preseed.cfg" ] || [ "../files/preseed.cfg" -nt "preseed.cfg" ]; then
	cp "../files/preseed.cfg" preseed.cfg
fi

if [ ! -e "initrd-mod.gz" ] || [ "preseed.cfg" -nt "initrd-mod.gz" ] || [ "initrd.gz" -nt "initrd-mod.gz" ]; then
	info "Creating updated initrd including preseed.cfg"
	rm -f initrd-mod.gz
	gunzip --keep initrd.gz
	echo preseed.cfg | cpio -H newc -o -A -F initrd --quiet
	mv initrd initrd-mod
	gzip initrd-mod
fi

if [ ! -d "ssh" ]; then
	mkdir "ssh"
fi
cd "ssh"

if [ ! -e "id_ed25519" ]; then
	info "Generating a SSH key"
	ssh-keygen -t ed25519 -f "id_ed25519" -C "debops-lab-${USER}" -N "" -q
fi

if [ ! -e "ssh_config" ]; then
	info "Installing custom ssh_config"
	cp "../../files/ssh_config" "./"
fi

if [ ! -d "hosts" ]; then
	mkdir "hosts"
fi

if [ ! -e ~/.ssh ]; then
	mkdir --mode=0700 ~/.ssh
fi

if [ ! -e ~/.ssh/debops-lab ]; then
	ln -sf "${PWD}" ~/.ssh/debops-lab
fi

info ""
exit 0
