#!/bin/bash

set -Eeuo pipefail
cd "${0%/*}"
. ./functions.sh

info "###########################"
info "# BOOT SERVER PREPARATION #"
info "###########################"

GUEST_NAME="boot"
GUEST_IP="192.168.99.253"

BOOT_APPEND="quiet"
BOOT_APPEND+=" DEBIAN_FRONTEND=text"
BOOT_APPEND+=" console=ttyS0,115200,n8"
BOOT_APPEND+=" auto=true"
BOOT_APPEND+=" priority=critical"
BOOT_APPEND+=" netcfg/disable_autoconfig=true"
BOOT_APPEND+=" netcfg/get_ipaddress=${GUEST_IP}"
BOOT_APPEND+=" netcfg/get_netmask=255.255.255.0"
BOOT_APPEND+=" netcfg/get_gateway=${DL_BRIDGE_ADDRESS}"
BOOT_APPEND+=" netcfg/get_nameservers=${DL_NAMESERVER}"
BOOT_APPEND+=" hostname=${GUEST_NAME}"
BOOT_APPEND+=" domain=${DL_DOMAIN}"

BOOT_ARGS=("-kernel" "./tmp/linux")
BOOT_ARGS+=("-initrd" "./tmp/initrd-mod.gz")
BOOT_ARGS+=("-append" "${BOOT_APPEND}")

start_vm "boot" "253" "${BOOT_ARGS[@]}"

info ""
exit 0
