#!/bin/bash

set -Eeuo pipefail
source "${0%/*}/functions.sh"

print_header "03 - BOOT SERVER PREPARATION"

if [ -z "${DL_BRIDGE_ADDRESS:-}" ]; then
	die "DL_BRIDGE_ADDRESS is not set"
elif [ -z "${DL_NAMESERVER:-}" ]; then
	die "DL_NAMESERVER is not set"
elif [ -z "${DL_DOMAIN:-}" ]; then
	die "DL_DOMAIN is not set"
fi

GUEST_NAME="boot"
GUEST_IP="192.168.99.253"

BOOT_APPEND="quiet"
BOOT_APPEND+=" DEBIAN_FRONTEND=text"
BOOT_APPEND+=" console=ttyS0,115200,n8"
BOOT_APPEND+=" auto=true"
BOOT_APPEND+=" priority=critical"
BOOT_APPEND+=" netcfg/disable_autoconfig=true"
BOOT_APPEND+=" netcfg/get_ipaddress=${GUEST_IP}"
BOOT_APPEND+=" netcfg/get_netmask=255.255.255.0"
BOOT_APPEND+=" netcfg/get_gateway=${DL_BRIDGE_ADDRESS}"
BOOT_APPEND+=" netcfg/get_nameservers=${DL_NAMESERVER}"
BOOT_APPEND+=" hostname=${GUEST_NAME}"
BOOT_APPEND+=" domain=${DL_DOMAIN}"

BOOT_ARGS=("-kernel" "./lab/linux")
BOOT_ARGS+=("-initrd" "./lab/initrd-mod.gz")
BOOT_ARGS+=("-append" "${BOOT_APPEND}")

start_vm "boot" "253" "${BOOT_ARGS[@]}"

finished
