#!/bin/bash

set -Eeuo pipefail
cd "${0%/*}"
. ./functions.sh

info "#############################"
info "# BOOT SERVER CONFIGURATION #"
info "#############################"

GUEST_NAME="boot"

activate_python_virtualenv

if [ ! -e "project" ]; then
	info "Creating DebOps project"
	debops project init "project" > /dev/null
	cd "./project"
	cp "../files/debops.cfg" "./.debops.cfg"
	debops project refresh > /dev/null
else
	cd "./project"
fi

#debops run bootstrap -l "${GUEST_NAME}" -e ansible_user=root
#debops run common -l "${HOST_NAME}"
#debops run service/tftpd -l "${HOST_NAME}"
#debops run service/dhcpd -l "${HOST_NAME}"
#debops run service/ipxe -l "${HOST_NAME}"

info "Host ${GUEST_NAME} configured"

info ""
exit 0
