#!/bin/bash

set -Eeuo pipefail
cd "${0%/*}"
. ./functions.sh

info "#############################"
info "# BOOT SERVER CONFIGURATION #"
info "#############################"

GUEST_NAME="boot"

activate_python_virtualenv

if [ ! -e "project" ]; then
	info "Creating DebOps project"
	debops project init "project" > /dev/null
	cd "./project"
	cp "../files/debops.cfg.template" "./.debops.cfg"
	echo "ssh_args = -F \"${HOME}/.ssh/debops-lab/ssh_config\"" >> "./.debops.cfg"
	rm -rf "./ansible/inventory"
	ln -sf "../../files/inventory" "./ansible/inventory"
	debops project refresh > /dev/null

	if [ ! -z "${DL_CUSTOM_DEBOPS_REPO}" ]; then
		git clone --quiet "${DL_CUSTOM_DEBOPS_REPO}" debops
		if [ ! -z "$DL_CUSTOM_DEBOPS_REPO_BRANCH" ]; then
			cd "./debops"
			git checkout "${DL_CUSTOM_DEBOPS_REPO_BRANCH}"
			cd ".."
		fi
		pip3 install --editable .
	fi
else
	cd "./project"
fi

export ANSIBLE_STRATEGY=mitogen_linear

debops run bootstrap -l "${GUEST_NAME}" -e ansible_user=root
debops run common -l "${GUEST_NAME}"
debops run service/tftpd -l "${GUEST_NAME}"
debops run service/dhcpd -l "${GUEST_NAME}"
debops run service/ipxe -l "${GUEST_NAME}"

info "Host ${GUEST_NAME} configured"

info ""
exit 0
