#!/bin/bash

set -Eeuo pipefail
cd "${0%/*}"
. ./functions.sh

info "#############################"
info "# BOOT SERVER CONFIGURATION #"
info "#############################"

GUEST_NAME="boot"

activate_python_virtualenv

if [ ! -e "project" ]; then
	info "Creating DebOps project"
	debops project init "project" > /dev/null
	cd "./project"
	cp "../files/debops.cfg.template" "./.debops.cfg"
	echo "ssh_args = -F \"${HOME}/.ssh/debops-lab/ssh_config\"" >> "./.debops.cfg"
	rm -rf "./ansible/inventory"
	ln -sf "../../files/inventory" "./ansible/inventory"
	debops project refresh > /dev/null
else
	cd "./project"
fi

export ANSIBLE_STRATEGY=mitogen_linear

debops run bootstrap -l "${GUEST_NAME}" -e ansible_user=root
#debops run common -l "${HOST_NAME}"
#debops run service/tftpd -l "${HOST_NAME}"
#debops run service/dhcpd -l "${HOST_NAME}"
#debops run service/ipxe -l "${HOST_NAME}"

info "Host ${GUEST_NAME} configured"

info ""
exit 0
