#!/bin/bash

set -Eeuo pipefail
cd "${0%/*}"
. ./functions.sh

info "############################"
info "# QTEST SERVER PREPARATION #"
info "############################"

info "Preparing to launch VM qtest1"
start_vm "qtest1" "1" &

info "Preparing to launch VM qtest2"
start_vm "qtest2" "2" &

info "Preparing to launch VM qtest3"
start_vm "qtest3" "3" &

wait
info "All subprocesses finished"

info ""
exit 0
