#!/bin/bash

set -Eeuo pipefail
cd "${0%/*}"
. ./functions.sh

print_header "ICINGA CONFIGURATION"

activate_python_virtualenv

cd "./project"

LDAPRC="$(pwd)/tmp/ldap.conf"
export LDAPRC
KRB5_CONFIG="$(pwd)/ansible/secret/kerberos/krb5.conf"
export KRB5_CONFIG

run_playbook "service/postgresql_server" "qtest1"

run_playbook "service/postgresql"

run_playbook "service/icinga" "qtest1"

run_playbook "service/icinga_db" "qtest1"

run_playbook "service/icinga_web" "qtest1"

# Run on all, including qtest1, so they register with the director
run_playbook "service/icinga"

print_info "Icinga configured"
print_info "Login: root"
print_info "Pass : $(cat ansible/secret/icinga_web/auth/qtest1/credentials/root/password)"

print_newline
exit 0
