#!/bin/bash

set -Eeuo pipefail
cd "${0%/*}"
. ./functions.sh

info "#########################"
info "# SETUP TEST USER (BOB) #"
info "#########################"

NEW_USER_NAME="bob"
NEW_USER_DN="uid=bob,ou=People,dc=example,dc=com"
LDAP_ADMIN_DN="uid=${USER},ou=People,dc=example,dc=com"
LDAP_ADMIN_PWD_FILE="$(pwd)/tmp/ldap_admin.pwd"
LDAP_CONF="$(pwd)/tmp/ldap.conf"
CUSTOM_HOSTS="$(pwd)/hosts"

export ANSIBLE_STRATEGY=mitogen_linear

activate_python_virtualenv

cd "./project"

export KRB5_CONFIG="./ansible/secret/kerberos/krb5.conf"
KRB5_KEYTAB="./ansible/secret/kerberos/admin.keytab"
KRB5_PRINC="${USER}/admin@EXAMPLE.COM"
export HOSTALIASES="${CUSTOM_HOSTS}"

info "Adding a relaxed Kerberos pwd policy for testing purposes"
kadmin -k -t "${KRB5_KEYTAB}" -p "${KRB5_PRINC}"			\
	addpol -minlength 1 -minclasses 1 testing

# Wrt -pwexpire, see https://github.com/SSSD/sssd/issues/6612
info "Adding a kerberos principal for user ${NEW_USER_NAME}"
kadmin -k -t "${KRB5_KEYTAB}" -p "${KRB5_PRINC}"			\
	addprinc -policy testing -pw 123abc				\
	-pwexpire "2030-01-01"						\
	+requires_preauth +lockdown_keys				\
	-x "dn=${NEW_USER_DN}"						\
	"${NEW_USER_NAME}"

info "New user ${NEW_USER_NAME} configured"

info ""
exit 0
